In [1]:
import numpy as np
import pandas as pd


In [2]:
data_file = '/content/drive/MyDrive/Colab Notebooks/projects/Data processing/makeSenseOfCensus.csv'

In [3]:
df= pd.read_csv(data_file)
df.head()

age  education-num  race  sex  capital-gain  capital-loss  hours-per-week  \
0   39             13     4    1          2174             0              40   
1   50             13     4    1             0             0              13   
2   38              9     4    1             0             0              40   
3   53              7     2    1             0             0              40   
4   28             13     2    0             0             0              40   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

In [4]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [5]:
data.shape

(1000, 8)

In [6]:
# step 2

new_record = np.array([[50, 9, 4, 1, 0, 0, 40, 0]])
data = np.concatenate((data,new_record),axis = 0)


In [7]:
print(data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [8]:
age = data[:,0]

max_age = age.max()
print(max_age)

90.0


In [9]:
min_age = age.min()
print(min_age)

17.0


In [10]:
age_mean = age.mean()
print(age_mean)

38.06293706293706


In [11]:
age_std = np.std(age)
print(age_std)

13.341478176165857


In [12]:
# step 4


Race=np.array(data[:,2])
race_a= Race==0
race_0=np.array(Race[race_a])
print(race_0)
Race=np.array(data[:,2])
race_b= Race==1
race_1=np.array(Race[race_b])
print(race_1)
Race=np.array(data[:,2])
race_c= Race==2
race_2=np.array(Race[race_c])
print(race_2)
Race=np.array(data[:,2])
race_d= Race==3
race_3=np.array(Race[race_d])
print(race_3)
Race=np.array(data[:,2])
race_e= Race==4
race_4=np.array(Race[race_e])
print(race_4)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4

In [13]:
sc=age>60
senior_citizen=data[:][sc]
print(senior_citizen)
print(len(senior_citizen))


[[7.9000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.7000e+01 6.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+00 0.0000e+00]
 [7.6000e+01 1.4000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 1.0000e+00]
 [6.1000e+01 9.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [7.0000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [6.4000e+01 7.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 2.1790e+03
  4.0000e+01 0.0000e+00]
 [7.1000e+01 1.0000e+01 2.0000e+00 1.0000e+00 0.0000e+00 1.8160e+03
  2.0000e+00 0.0000e+00]
 [6.8000e+01 2.0000e+00 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.6000e+01 1.1000e+01 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.4000e+01 2.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [9.0000e+01 9.0000e+00 2.0000e+00 1.0000e+00 0.0000e+00 2.2060e+03
  

In [14]:
working_hour=np.array(senior_citizen[:,6])
print(working_hour)
working_hours_sum=working_hour.sum()
print(working_hours_sum)


[20.  2. 40. 40. 40. 40.  2. 20. 20. 40. 40. 50. 20. 40. 40. 40. 16. 40.
 24. 10. 45. 55.  8. 40. 40. 40. 24. 24. 35. 20. 40.  9. 48. 40. 40. 30.
 24. 15. 15.  4. 59. 50. 40. 20. 40. 45. 40. 40. 24.  6. 48. 40. 40. 15.
 55. 40. 30.  5. 40. 40. 20.]
1917.0


In [15]:
avg_working_hour=np.mean(working_hour)
print(avg_working_hour)


31.42622950819672


In [16]:
education_num=np.array(data[:,1])
print(education_num)


[13. 13.  9. ... 10. 13.  9.]


In [17]:
high=education_num>10
low=education_num<=10
High=np.array(data[high])
Low=np.array(data[low])
print(High)
print(Low)
print(High.shape)
print(Low.shape)


[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]
[[38.  9.  4. ...  0. 40.  0.]
 [53.  7.  2. ...  0. 40.  0.]
 [49.  5.  2. ...  0. 16.  0.]
 ...
 [56.  9.  4. ...  0. 55.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]
(327, 8)
(674, 8)


In [18]:
avg_highpay=High.mean()
print(avg_highpay)

167.18119266055047


In [19]:
avg_lowpay=Low.mean()
print(avg_lowpay)

62.46494807121662
